import Footer from './_components/Footer'
import NavBar from './_components/NavBar'
import About from './_components/About';
import Verticals from './_components/Verticals';
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '900']
})

export const metadata = {
  title: 'Tech Multiverse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar/>
        {children}
        <About/>
        <Verticals/>
        <Footer />
        </body>
    </html>
  )
}
