import NavBar from './_components/NavBar';
import About from './_components/About';
import Verticals from './_components/Verticals';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tech Metaverse',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        
        {children}
        <About/>
        <Verticals/>
        </body>
    </html>
  )
}
